config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :standbies, only: [:create, :destroy]
  resources :matches, only: :create
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form containts <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/shared/_match_form.html.erb
<% if current_user.admin? %>
  <%= link_to "マッチを作成する", matches_path, method: :create %>
<% end %>

app/views/shared/_standby_form.html.erb
<%= form_for(@standby) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :予約日時 %>
  <%= f.date_field :date, class: 'form-control' %>

  <%= f.submit "ランチGO!の予約をする", class: "btn btn-primary" %>
<% end %>

app/views/shared/_standby_reservations.html.erb
<h3>ランチGO!予約一覧 (<%= @standby_reservations.count %>)</h3>
<% if @standby_reservations.any? %>
  <ul class="standby_reservations">
    <%= render @standby_reservations %>
  </ul>
  <%= will_paginate @standby_reservations %>
<% else %>
  <p>ランチGO!の予約はありません</p>
<% end %>

app/views/shared/_standby_today_form.html.erb
<%= form_for @standby, html: { class: 'form-small' }  do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.hidden_field :user_id, value: user.id, class: 'form-control' %>
  <%= f.hidden_field :date, value: Time.zone.today, class: 'form-control' %>

  <%= f.submit "強制予約", class: "btn btn-primary btn-small" %>
<% end %>

app/views/shared/_todays_match.html.erb
<h3>本日のランチ相手</h3>
<% if @todays_home && @todays_away %>
  <ul class="today_match">
    <li>Home | <%= @todays_home.name %> (お店を決めてください)</li>
    <li>Away | <%= @todays_away.name %></li>
    <% if @todays_referee %>
      <li>審判 | <%= @todays_referee.name %></li>
    <% end %>
  </ul>
<% else %>
  <p>本日のランチ相手はまだいません（毎日11:30〜12:00にお相手が決まります）</p>
<% end %>